title: "Riaz.Codes Blog"
description: "Riaz.Codes Blog"
tagline: 'Riaz.thoughts.each { |thought| write }'

baseurl: http://riaz.codes/
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: UA-53554002-1

owner:
  name: "Riaz Virani"
  disqus_shortname: riazcodes
  twoople: riaz
