title: "Riaz.Codes Blog"
description: "Riaz.Codes Blog"

baseurl: http://riaz.codes/
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: "Riaz Virani"
  disqus_shortname: riazvirani
  twitter: _nadjetey
